/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import db.entitas.Stasiun_Entitas;
import db.services.Stasiun_Service;
import javax.swing.JOptionPane;

/**
 *
 * @author adisa
 */
public class Panel_Stasiun extends javax.swing.JPanel {

    private Stasiun_Service stasiun_Service;

    /**
     * Creates new form Panel_Kelas_KAI
     */
    public Panel_Stasiun() {
        initComponents();
        stasiun_Service = new Stasiun_Service();

        tableStasiun.setModel(stasiun_Service.read());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textIdStasiun = new javax.swing.JTextField();
        textNamaStasiun = new javax.swing.JTextField();
        buttonInsert_Stasiun = new javax.swing.JButton();
        buttonUpdate_Stasiun = new javax.swing.JButton();
        buttonDelete_Stasiun = new javax.swing.JButton();
        buttonClear_Stasiun = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStasiun = new javax.swing.JTable();

        jLabel1.setText("ID Stasiun :");

        jLabel2.setText("Nama Stasiun  :");

        buttonInsert_Stasiun.setText("Insert");
        buttonInsert_Stasiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsert_StasiunActionPerformed(evt);
            }
        });

        buttonUpdate_Stasiun.setText("Update");
        buttonUpdate_Stasiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdate_StasiunActionPerformed(evt);
            }
        });

        buttonDelete_Stasiun.setText("Delete");
        buttonDelete_Stasiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete_StasiunActionPerformed(evt);
            }
        });

        buttonClear_Stasiun.setText("Clear");
        buttonClear_Stasiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear_StasiunActionPerformed(evt);
            }
        });

        tableStasiun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStasiun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStasiunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStasiun);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonInsert_Stasiun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonUpdate_Stasiun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonDelete_Stasiun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonClear_Stasiun))
                                    .addComponent(textIdStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIdStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsert_Stasiun)
                    .addComponent(buttonUpdate_Stasiun)
                    .addComponent(buttonDelete_Stasiun)
                    .addComponent(buttonClear_Stasiun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsert_StasiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsert_StasiunActionPerformed
        // TODO add your handling code here:
        Stasiun_Entitas stasiun = new Stasiun_Entitas();
        stasiun.setId_stasiun(textIdStasiun.getText());
          stasiun.setNama_stasiun(textNamaStasiun.getText());
//        kelas_KAI.setHarga(Integer.parseInt(textNamaStasiun.getText()));

        if (stasiun_Service.insert(stasiun)) {
            JOptionPane.showMessageDialog(null, "Insert Stasiun Berhasil");
        }
        
        tableStasiun.setModel(stasiun_Service.read());

    }//GEN-LAST:event_buttonInsert_StasiunActionPerformed

    private void buttonUpdate_StasiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdate_StasiunActionPerformed
        // TODO add your handling code here:
        Stasiun_Entitas stasiun2 = new Stasiun_Entitas();
         stasiun2.setId_stasiun(textIdStasiun.getText());
          stasiun2.setNama_stasiun(textNamaStasiun.getText());
        if (stasiun_Service.update(stasiun2)) {
            JOptionPane.showMessageDialog(null, "Update Data Stasiun KAI Berhasil");
        }
        
        tableStasiun.setModel(stasiun_Service.read());
    }//GEN-LAST:event_buttonUpdate_StasiunActionPerformed

    private void buttonDelete_StasiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete_StasiunActionPerformed
        // TODO add your handling code here:
        if (stasiun_Service.delete(textIdStasiun.getText())) {
            JOptionPane.showMessageDialog(null, "Hapus Data Stasiun KAI Berhasil");
        }
        
        tableStasiun.setModel(stasiun_Service.read());
    }//GEN-LAST:event_buttonDelete_StasiunActionPerformed

    private void tableStasiunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStasiunMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableStasiun.getSelectedRow();
        if(selectedRow != -1){
            textIdStasiun.setText(tableStasiun.getValueAt(selectedRow, 0).toString());
            textNamaStasiun.setText(tableStasiun.getValueAt(selectedRow, 1).toString());
        }
    }//GEN-LAST:event_tableStasiunMouseClicked

    private void buttonClear_StasiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear_StasiunActionPerformed
        // TODO add your handling code here:
        textNamaStasiun.setText("");
        textIdStasiun.setText("");
        
        tableStasiun.setModel(stasiun_Service.read());
    }//GEN-LAST:event_buttonClear_StasiunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear_Stasiun;
    private javax.swing.JButton buttonDelete_Stasiun;
    private javax.swing.JButton buttonInsert_Stasiun;
    private javax.swing.JButton buttonUpdate_Stasiun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableStasiun;
    private javax.swing.JTextField textIdStasiun;
    private javax.swing.JTextField textNamaStasiun;
    // End of variables declaration//GEN-END:variables
}
