/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import db.entitas.Kelas_KAI_Entitas;
import db.services.Kelas_KAI_Service;
import javax.swing.JOptionPane;

/**
 *
 * @author adisa
 */
public class Panel_Kelas_KAI extends javax.swing.JPanel {

    private Kelas_KAI_Service kelas_KAI_Service;

    /**
     * Creates new form Panel_Kelas_KAI
     */
    public Panel_Kelas_KAI() {
        initComponents();
        kelas_KAI_Service = new Kelas_KAI_Service();

        tableKelasKAI.setModel(kelas_KAI_Service.read());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textIdKelas = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        buttonInsert_Kelas = new javax.swing.JButton();
        buttonUpdate_Kelas = new javax.swing.JButton();
        buttonDelete_Kelas = new javax.swing.JButton();
        buttonClear_Kelas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKelasKAI = new javax.swing.JTable();

        jLabel1.setText("ID Kelas :");

        jLabel2.setText("Harga :");

        buttonInsert_Kelas.setText("Insert");
        buttonInsert_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsert_KelasActionPerformed(evt);
            }
        });

        buttonUpdate_Kelas.setText("Update");
        buttonUpdate_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdate_KelasActionPerformed(evt);
            }
        });

        buttonDelete_Kelas.setText("Delete");
        buttonDelete_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete_KelasActionPerformed(evt);
            }
        });

        buttonClear_Kelas.setText("Clear");
        buttonClear_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear_KelasActionPerformed(evt);
            }
        });

        tableKelasKAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKelasKAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKelasKAIMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKelasKAI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonInsert_Kelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonUpdate_Kelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonDelete_Kelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonClear_Kelas))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textIdKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(textHarga))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsert_Kelas)
                    .addComponent(buttonUpdate_Kelas)
                    .addComponent(buttonDelete_Kelas)
                    .addComponent(buttonClear_Kelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsert_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsert_KelasActionPerformed
        // TODO add your handling code here:
        Kelas_KAI_Entitas kelas_KAI = new Kelas_KAI_Entitas();
        kelas_KAI.setId_kelas(textIdKelas.getText());
        kelas_KAI.setHarga(Integer.parseInt(textHarga.getText()));

        if (kelas_KAI_Service.insert(kelas_KAI)) {
            JOptionPane.showMessageDialog(null, "Insert Data Kelas KAI Berhasil");
        }
        
        tableKelasKAI.setModel(kelas_KAI_Service.read());

    }//GEN-LAST:event_buttonInsert_KelasActionPerformed

    private void buttonUpdate_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdate_KelasActionPerformed
        // TODO add your handling code here:
        Kelas_KAI_Entitas kelas_KAI = new Kelas_KAI_Entitas();
        kelas_KAI.setId_kelas(textIdKelas.getText());
        kelas_KAI.setHarga(Integer.parseInt(textHarga.getText()));

        if (kelas_KAI_Service.update(kelas_KAI)) {
            JOptionPane.showMessageDialog(null, "Update Data Kelas KAI Berhasil");
        }
        
        tableKelasKAI.setModel(kelas_KAI_Service.read());
    }//GEN-LAST:event_buttonUpdate_KelasActionPerformed

    private void buttonDelete_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete_KelasActionPerformed
        // TODO add your handling code here:
        if (kelas_KAI_Service.delete(textIdKelas.getText())) {
            JOptionPane.showMessageDialog(null, "Hapus Data Kelas KAI Berhasil");
        }
        
        tableKelasKAI.setModel(kelas_KAI_Service.read());
    }//GEN-LAST:event_buttonDelete_KelasActionPerformed

    private void tableKelasKAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKelasKAIMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableKelasKAI.getSelectedRow();
        if(selectedRow != -1){
            textIdKelas.setText(tableKelasKAI.getValueAt(selectedRow, 0).toString());
            textHarga.setText(tableKelasKAI.getValueAt(selectedRow, 1).toString());
        }
    }//GEN-LAST:event_tableKelasKAIMouseClicked

    private void buttonClear_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear_KelasActionPerformed
        // TODO add your handling code here:
        textHarga.setText("");
        textIdKelas.setText("");
        
        tableKelasKAI.setModel(kelas_KAI_Service.read());
    }//GEN-LAST:event_buttonClear_KelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear_Kelas;
    private javax.swing.JButton buttonDelete_Kelas;
    private javax.swing.JButton buttonInsert_Kelas;
    private javax.swing.JButton buttonUpdate_Kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableKelasKAI;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textIdKelas;
    // End of variables declaration//GEN-END:variables
}
